add_custom_command(
    TARGET ${PROJECT_NAME}
    POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_if_different $<TARGET_FILE:${PROJECT_NAME}> ${BAKKESMOD_PREFIX}/$<TARGET_FILE_BASE_NAME:${PROJECT_NAME}>.dll
    COMMAND ${CMAKE_COMMAND} -E copy_if_different $<TARGET_PDB_FILE:${PROJECT_NAME}> ${BAKKESMOD_PREFIX}/$<TARGET_FILE_BASE_NAME:${PROJECT_NAME}>.pdb
)
